### ISSUE TITLE
p.138 3.8.2 SSG를 통한 페이지 구현 오타

### ISSUE THREAD

**Issue by 0r0loo** [wikibook/typescript-and-nextjs#2]
우선, ~~ 첫번째줄
ssg.txt => ssg.tsx

**Comment by wikibook** [comment]
@0r0loo  님, 안녕하세요.
위키북스 담당자입니다.

보내주신 내용을 확인했는데, 138쪽 내용은 말씀하신 대로 수정해야 맞습니다.

해당 내용을 홈페이지 정오표 탭에 등록했습니다. 불편을 드려서 죄송하고, 오류를 바로잡을 수 있게 알려주셔서 감사합니다. 수정된 내용은 다음 번에 인쇄할 때 반영하도록 하겠습니다.

https://wikibook.co.kr/ts-react-nextjs/

그럼 오늘도 좋은 하루 보내세요!
고맙습니다.
